import { signIn } from 'next-auth/react'
import React, { useState } from 'react';
import { useRouter } from 'next/router'
import Head from 'next/head'
import MainNavbar from 'components/MainNavbar';
import Fab from '@mui/material/Fab';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Form, } from 'react-bootstrap';
import AddIcon from '@mui/icons-material/Add';
import LoginIcon from '@mui/icons-material/Login';
import Grid from '@mui/material/Grid';
import Link from 'next/link'

function SignIn() {
  const [identifier, setIdentifier] = useState('')
  const [password, setPassword] = useState('')
  const router = useRouter()

  const handleSubmit = async (e) => {
    e.preventDefault()
    const result = await signIn('credentials', {
      identifier,
      password,
      redirect: false // Prevents automatic redirection after sign in.
    })
    if (result.error) {
      console.log('Failed to sign in:', result.error)
      return
    }
    // Sign in successful.
    // Redirect the user to the home page or some other protected page.
    // You can use the `router` object from the `next/router` module for this.
    router.push('/')
  }

  return (
    <>
      <Head>
        <title>Gadgets Galore</title> 
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <MainNavbar/>
      <Box sx={{  width: '95%', m:'auto', mt: 10, bgcolor: 'transparent', overflow: 'auto', filter: 'drop-shadow(5px 5px 5px rgba(0,0,0,0.63))'}}>
        <Grid container spacing={{ xs: 1, md: 1 }} columns={{ xs: 4, sm: 8, md: 13 }} sx={{m: 'auto', textAlign: 'center'}}>
          <Grid item xs={5} sx={{ m: 'auto', bgcolor: 'transparent',  borderRadius: '16px', overflow: 'auto'}} className="svcGrid">
            <Typography sx={{ fontSize: 18 }} color="text.secondary" gutterBottom>
              Sign In to your account or <Link href='/Register' className='listItem'>Create a new one</Link>
            </Typography>
            <br></br>
            <Form onSubmit={handleSubmit}>
              <Form.Group controlId="formBasicEmail">
                <Form.Label style={{float: 'left', marginLeft: '20px'}}>Email</Form.Label>
                <Form.Control type="email" placeholder="Enter Email" value={identifier} onChange={(e) => setIdentifier(e.target.value)} style={{backgroundColor: 'transparent', border: '1px solid black', }}/>
              </Form.Group>
              <br></br>
              <Form.Group controlId="formBasicEmail">
                <Form.Label style={{float: 'left', marginLeft: '20px'}}>Password</Form.Label>
                <Form.Control type="password" placeholder="Enter Password" value={password} onChange={(e) => setPassword(e.target.value)} style={{backgroundColor: 'transparent', border: '1px solid black', }}/>
              </Form.Group>
              <br></br>
              <Fab variant="extended" type="submit" sx={{ mt: 2, backgroundColor: '#7b54bf', '&:hover': {backgroundColor : '#9256fa'}, }}>
                <LoginIcon sx={{ mr: 1 }} />
                Sign in 
              </Fab>
              <br></br>
              <br></br>
            </Form>
          </Grid>
        </Grid>
        <br></br>
      </Box>
    {/* <form onSubmit={handleSubmit}>
      <label>
        Email:
        <input type="email" value={identifier} onChange={(e) => setIdentifier(e.target.value)} />
      </label>
      <label>
        Password:
        <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
      </label>
      <button type="submit">Sign in</button>
    </form> */}
    </>
  )
}

export default SignIn






