import React, { useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import { signIn } from 'next-auth/react'
import Head from 'next/head'
import MainNavbar from 'components/MainNavbar';
import Fab from '@mui/material/Fab';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Form, } from 'react-bootstrap';
import AddIcon from '@mui/icons-material/Add';
import LoginIcon from '@mui/icons-material/Login';
import Grid from '@mui/material/Grid';
import Link from 'next/link'

const Register = () => {
  const router = useRouter();
  const [userData, setUserData] = useState({
    username: '',
    email: '',
    password: '',
  })

  const handleSubmit = async (e) => {
    console.log(userData)
    e.preventDefault();
    try {
      await axios.post('/api/register', userData);
      router.replace('/');
    } catch (err) {
      console.log(err.response.data);
    }
  }

  const handleChange = (e) => {
    const { name, value } = e.target;
    setUserData({...userData, [name]: value });
  }

  return (
    <>
    <Head>
        <title>Gadgets Galore</title> 
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <MainNavbar/>
      <Box sx={{  width: '95%', m:'auto', mt: 10, bgcolor: 'transparent', overflow: 'auto', filter: 'drop-shadow(5px 5px 5px rgba(0,0,0,0.63))'}}>
        <Grid container spacing={{ xs: 1, md: 1 }} columns={{ xs: 4, sm: 8, md: 13 }} sx={{m: 'auto', textAlign: 'center'}}>
          <Grid item xs={5} sx={{ m: 'auto', bgcolor: 'transparent',  borderRadius: '16px', overflow: 'auto'}} className="svcGrid">
            <Typography sx={{ fontSize: 18 }} color="text.secondary" gutterBottom>
              Create a new account or <Link href='/Login' className='listItem'>Sign In</Link>
            </Typography>
            <br></br>
            <Form onSubmit={handleSubmit}>
              <Form.Group>
                <Form.Label style={{float: 'left', marginLeft: '20px'}}>User Name</Form.Label>
                <Form.Control type="text" name="username" placeholder="Enter User Name" onChange={e => handleChange(e)} style={{backgroundColor: 'transparent', border: '1px solid black', }}/>
              </Form.Group>
              <br></br>
              <Form.Group>
                <Form.Label style={{float: 'left', marginLeft: '20px'}}>Email</Form.Label>
                <Form.Control type="email" name="email" placeholder="Enter Email" onChange={e => handleChange(e)} style={{backgroundColor: 'transparent', border: '1px solid black', }}/>
              </Form.Group>
              <br></br>
              <Form.Group>
                <Form.Label style={{float: 'left', marginLeft: '20px'}}>Password</Form.Label>
                <Form.Control type="password" name="password" placeholder="Enter Password" onChange={e => handleChange(e)} style={{backgroundColor: 'transparent', border: '1px solid black', }}/>
              </Form.Group>
              <br></br>
              <Fab variant="extended" type="submit" sx={{ mt: 2, backgroundColor: '#7b54bf', '&:hover': {backgroundColor : '#9256fa'}, }}>
                <LoginIcon sx={{ mr: 1 }} />
                Sign up 
              </Fab>
              <br></br>
              <br></br>
            </Form>
          </Grid>
        </Grid>
        <br></br>
      </Box>
    {/* <form onSubmit={handleSubmit}>
      <label>
        Username:
        <input type="text" name="username" onChange={e => handleChange(e)} />
      </label>
      <br />
      <label>
        Email:
        <input type="text" name="email" onChange={e => handleChange(e)} />
      </label>
      <br />
      <label>
        Password:
        <input type="password" name="password" onChange={e => handleChange(e)} />
      </label>
      <br />
      <button>Register</button>
    </form> */}
    </>
  )
}

export default Register;