import React, {useState, useEffect} from 'react'
import { useRouter } from 'next/router';
import 'bootstrap/dist/css/bootstrap.min.css';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import Typography from '@mui/material/Typography';
import Fab from '@mui/material/Fab';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import AddIcon from '@mui/icons-material/Add';
import DashDrawer from 'components/DashDrawer';
import RevenueChart from 'components/RevenueChart';
import UserChart from 'components/UserChart';
import AddProduct from 'components/AddProduct';
import { signOut, useSession } from "next-auth/react"
import MainNavbar from 'components/MainNavbar';
import Link from 'next/link'


export default function Home(props) {

    
    // const { data: session } = useSession();
    const { data: session, status } = useSession();
    const user = session?.user;
    console.log(user)

    const router = useRouter();
    // router.replace('/');

    if(user && user.role === "admin"){
        return (
          <>
            <Head>
              <title>Dashboard</title> 
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/logo.png" />
            </Head>
            <section>
                <DashDrawer/>
            </section>
            <br></br>
            <section>
                <AddProduct/>
            </section>
            <br></br>
            <section>
                <Box sx={{  width: '95%', m:'auto', mt: 2, bgcolor: 'transparent', overflow: 'auto', filter: 'drop-shadow(1px 1px 1px rgba(0,0,0,0.63))'}} >
                    <Grid container spacing={2} sx={{mt: 1}}>
                        <Grid item md={7} >
                            <Box sx={{ m: 'auto', filter: 'drop-shadow(5px 5px 5px rgba(0,0,0,0.63))', bgcolor: 'transparent',  borderRadius: '16px',  overflow: 'auto'}}>
                                <Typography variant="h5" gutterBottom sx={{textAlign: 'center' }}>
                                    Revenue Data
                                </Typography>
                                <RevenueChart/>
                            </Box>        
                        </Grid>
                        <Grid item md={5}>
                            <Box sx={{ m: 'auto', filter: 'drop-shadow(5px 5px 5px rgba(0,0,0,0.63))', bgcolor: 'transparent',  borderRadius: '16px',  overflow: 'auto'}}>
                                <Typography variant="h5" gutterBottom sx={{textAlign: 'center' }}>
                                    Users Data
                                </Typography>
                                <UserChart/>
                            </Box>        
                        </Grid>
                    </Grid>
                    <br></br>
                </Box>
                
            </section>
          </>
        )

    }
    
    return(
        <>
            <Head>
                <title>Gadgets Galore</title> 
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <section>
                <MainNavbar/>
            </section>
            <section>
                <Box sx={{textAlign: 'center', mt: '5%' }}>
                    <Typography variant="h5" gutterBottom >
                        Please <Link href='/Login' className='listItem'>SignIn</Link> or <Link href='/Register' className='listItem'>Create</Link> an account
                        to continue.
                    </Typography>
                </Box>
            </section>
        </>
    )

    // if(!user){

    // }
    // else{
    //     router.push('/');
    //     return(
    //         <>
    //             <Head>
    //                 <title>Gadgets Galore</title> 
    //                 <meta name="description" content="Generated by create next app" />
    //                 <meta name="viewport" content="width=device-width, initial-scale=1" />
    //                 <link rel="icon" href="/logo.png" />
    //             </Head>
    //             <section>
    //                 <MainNavbar/>
    //             </section>
    //         </>
    //     )
    //     // return null;
    // }
  
  }